title: via Silvia
theme: jekyll-theme-minimal
logo: /logo.png
nav:
  - title: "About"
    url: /
  - title: "CV"
    url: /cv/
github:
  scholar_url: https://scholar.google.com/citations?user=RZadS3UAAAAJ&hl=en&oi=ao
  linkedin_url: https://www.linkedin.com/in/silvia-cazacu/
  cv_url: /cv/ #test
